[Task-04] Max Snischuk - Styling in React
snischuk/fe-react-2024 pull request #4
Opened 2024-05-18 12:29 UTC by snischuk

***[Link to deployment](https://snischuk.github.io/fe-react-2024/)***

***Acceptance criteria for 1***

- [ ] Mentor is added to pr
- [ ] AC copied to pr description
- [ ] Link to deployed version is added to pr
- [ ] Added layout of `Search Bar`
- [ ] Rewritten all styles with `Module Styles`
- [ ] Implemented `dynamic theme change` logic
 
***Acceptance criteria for 1****

- [ ] Implemented logic for fetching `user's theme`.
- [ ] Saved theme to the `Local storage`.
Note: if we have saved theme in `Local storage`, we use it first after reloading of the page

2024-05-19 08:22 UTC, vladyslav-yermolin-moc approved these changes
Good work!

2024-05-19 08:22 UTC, vladyslav-yermolin-moc commented on src/components/About/About.module.css
Hey, @snischuk do you like this layout? It looks a bit odd to me...
If you have decided to use a decoration image, you could switch it to the orange one for the light theme, like on the design. Up to you
![image](https://github.com/snischuk/fe-react-2024/assets/98031768/63970845-0db7-4cf2-a39e-053a0afee6f7)
<img width="731" alt="image" src="https://github.com/snischuk/fe-react-2024/assets/98031768/b78b81e9-ac6d-42d1-a500-47435acaaee7">

2024-05-19 08:22 UTC, vladyslav-yermolin-moc commented on src/App.tsx
> +            return isUserSystemThemeLight ? ThemeMode.LIGHT : ThemeMode.DARK;
You can make a `theme.service.ts` or `theme.helper.ts` file and move to it all logic related to the theme.
E.g. this could be `getSystemTheme`

2024-05-19 08:22 UTC, vladyslav-yermolin-moc commented on src/App.tsx
> +        document.documentElement.dataset.theme = currentTheme;
I beleive the `currentTheme` is just a string so you can save it without stringifying
```suggestion
        saveThemeToLocalStarage(LS_KEY_THEME_MODE, currentTheme) 
```

2024-05-19 08:22 UTC, vladyslav-yermolin-moc commented on src/components/ControlPanel/ControlPanel.module.css
> +@media (width >=769px) {
Please correct to the design 
![image](https://github.com/snischuk/fe-react-2024/assets/98031768/e60a3cb4-72e4-47c0-864a-52ddb4e87a9b)

2024-05-19 08:22 UTC, vladyslav-yermolin-moc commented on src/components/ControlPanel/ControlPanel.tsx
> +            <select className={styles.sortSelect} name="sort" id="sort">
Please add an arrow 
<img width="467" alt="image" src="https://github.com/snischuk/fe-react-2024/assets/98031768/91e18c83-6d5b-44d9-b2f2-1426f4655ca6">

2024-05-19 08:22 UTC, vladyslav-yermolin-moc commented on src/components/ProductCard/ProductCard.module.css
Please enhance your cart logic: add the indicator to the Product card icon 
<img width="817" alt="image" src="https://github.com/snischuk/fe-react-2024/assets/98031768/df60bb6d-83fc-4b06-b3c2-a568649030ba">

2024-05-19 08:23 UTC, vladyslav-yermolin-moc requested changes
Sorry, misclicked to Approve

2024-05-21 11:30 UTC, snischuk commented
All fixed

2024-05-21 16:32 UTC, vladyslav-yermolin-moc commented on src/components/ControlPanel/ControlPanel.tsx
> +            <select className={styles.sortSelect} name="sort" id="sort">
Magic )))
<img width="674" alt="image" src="https://github.com/snischuk/fe-react-2024/assets/98031768/f8918b52-7dbb-4395-826b-d40154f5d82b">

2024-05-21 16:33 UTC, vladyslav-yermolin-moc approved these changes

2024-05-21 16:34 UTC, vladyslav-yermolin-moc commented on src/components/ControlPanel/ControlPanel.tsx
> +            <select className={styles.sortSelect} name="sort" id="sort">
please fix in the next pr

2024-05-21 16:34 UTC, merged